/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_bastoup_spigotplusplus_link_CPPLink */

#ifndef _Included_fr_bastoup_spigotplusplus_link_CPPLink
#define _Included_fr_bastoup_spigotplusplus_link_CPPLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_bastoup_spigotplusplus_link_CPPLink
 * Method:    loadPlugin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_bastoup_spigotplusplus_link_CPPLink_loadPlugin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_bastoup_spigotplusplus_link_CPPLink
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fr_bastoup_spigotplusplus_link_CPPLink_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
