name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: APT Update
      run: sudo apt update
    - name: Test
      run: sudo apt-cache search aarch64-linux-gnu
    - name: Install Dependencies
      run: sudo apt install -y make cmake gcc-multilib g++-multilib gcc gcc-mingw-w64 gcc-9-arm-linux-gnueabi gcc-9-aarch64-linux-gnu g++ g++-mingw-w64 g++-9-arm-linux-gnueabi g++-9-aarch64-linux-gnu binutils binutils-mingw-w64 binutils-9-arm-linux-gnueabi binutils-9-aarch64-linux-gnu openjdk-16-jdk
    - name: make
      run: make
